import Link from 'next/link'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className={inter.className + " flex flex-col h-screen"}>
                <div className='m-auto rounded-lg overflow-hidden bg-gray-300 flex flex-col'>
                    <nav className="flex justify-center gap-5 bg-indigo-400 mb-5 px-5">
                        <Link href={"/books"}>Books</Link>
                        <Link href={"/members"}>Members</Link>
                        <Link href={"/loaned"}>Loaned</Link>
                        <Link href={"/shelves"}>Shelves</Link>
                        <Link href={"/addresses"}>Addresses</Link>
                    </nav>
                    <main className="flex items-center flex-col bg-purple-300">
                        {children}
                    </main>
                </div>
            </body>
        </html>
    )
}
